In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("../vehicles_us.csv")

In [16]:
df.head()

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
0,9400,2011.0,bmw x5,good,6.0,gas,145000.0,automatic,SUV,NaN,1.0,2018-06-23,19
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
2,5500,2013.0,hyundai sonata,like new,4.0,gas,110000.0,automatic,sedan,red,NaN,2019-02-07,79
3,1500,2003.0,ford f-150,fair,8.0,gas,NaN,automatic,pickup,NaN,NaN,2019-03-22,9
4,14900,2017.0,chrysler 200,excellent,4.0,gas,80903.0,automatic,sedan,black,NaN,2019-04-02,28

In [17]:
df.shape

(51525, 13)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   price         51525 non-null  int64
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  str
 3   condition     51525 non-null  str
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  str
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  str
 8   type          51525 non-null  str
 9   paint_color   42258 non-null  str
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  str
 12  days_listed   51525 non-null  int64
dtypes: float64(4), int64(2), str(7)
memory usage: 7.7 MB

In [19]:
df.isna().sum()

price               0
model_year       3619
model               0
condition           0
cylinders        5260
fuel                0
odometer         7892
transmission        0
type                0
paint_color      9267
is_4wd          25953
date_posted         0
days_listed         0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.describe()

,price,model_year,cylinders,odometer,is_4wd,days_listed
count,51525.000000,47906.000000,46265.000000,43633.000000,25572.0,51525.00000
mean,12132.464920,2009.750470,6.125235,115553.461738,1.0,39.55476
std,10040.803015,6.282065,1.660360,65094.611341,0.0,28.20427
min,1.000000,1908.000000,3.000000,0.000000,1.0,0.00000
25%,5000.000000,2006.000000,4.000000,70000.000000,1.0,19.00000
50%,9000.000000,2011.000000,6.000000,113000.000000,1.0,33.00000
75%,16839.000000,2014.000000,8.000000,155000.000000,1.0,53.00000
max,375000.000000,2019.000000,12.000000,990000.000000,1.0,271.00000

In [22]:
# Valores únicos de las variables categóricas

print("Condition:")
print(df["condition"].unique())

print("\nFuel:")
print(df["fuel"].unique())

print("\nTransmission:")
print(df["transmission"].unique())

print("\nType:")
print(df["type"].unique())

print("\n4WD:")
print(df["is_4wd"].unique())

Condition:
<ArrowStringArray>
['good', 'like new', 'fair', 'excellent', 'salvage', 'new']
Length: 6, dtype: str

Fuel:
<ArrowStringArray>
['gas', 'diesel', 'other', 'hybrid', 'electric']
Length: 5, dtype: str

Transmission:
<ArrowStringArray>
['automatic', 'manual', 'other']
Length: 3, dtype: str

Type:
<ArrowStringArray>
[        'SUV',      'pickup',       'sedan',       'truck',       'coupe',
         'van', 'convertible',   'hatchback',       'wagon',    'mini-van',
       'other',     'offroad',         'bus']
Length: 13, dtype: str

4WD:
[ 1. nan]

In [23]:

df["condition"].value_counts()

condition
excellent    24773
good         20145
like new      4742
fair          1607
new            143
salvage        115
Name: count, dtype: int64

In [24]:
df["fuel"].value_counts()

fuel
gas         47288
diesel       3714
hybrid        409
other         108
electric        6
Name: count, dtype: int64

In [25]:
df["transmission"].value_counts()

transmission
automatic    46902
manual        2829
other         1794
Name: count, dtype: int64

In [26]:
df["type"].value_counts()

type
SUV            12405
truck          12353
sedan          12154
pickup          6988
coupe           2303
wagon           1541
mini-van        1161
hatchback       1047
van              633
convertible      446
other            256
offroad          214
bus               24
Name: count, dtype: int64

In [27]:
df["is_4wd"].value_counts(dropna=False)

is_4wd
NaN    25953
1.0    25572
Name: count, dtype: int64

In [28]:
df.describe()

,price,model_year,cylinders,odometer,is_4wd,days_listed
count,51525.000000,47906.000000,46265.000000,43633.000000,25572.0,51525.00000
mean,12132.464920,2009.750470,6.125235,115553.461738,1.0,39.55476
std,10040.803015,6.282065,1.660360,65094.611341,0.0,28.20427
min,1.000000,1908.000000,3.000000,0.000000,1.0,0.00000
25%,5000.000000,2006.000000,4.000000,70000.000000,1.0,19.00000
50%,9000.000000,2011.000000,6.000000,113000.000000,1.0,33.00000
75%,16839.000000,2014.000000,8.000000,155000.000000,1.0,53.00000
max,375000.000000,2019.000000,12.000000,990000.000000,1.0,271.00000

In [29]:
df["price"].sort_values().head(10)

8115     1
11634    1
3063     1
11402    1
11633    1
11632    1
11631    1
11630    1
40243    1
11629    1
Name: price, dtype: int64

In [30]:
df["price"].sort_values(ascending=False).head(10)

12504    375000
11359    300000
34389    189000
1309     189000
27375    189000
1668     189000
33434    189000
30634    189000
34206    175000
41748    145000
Name: price, dtype: int64

In [31]:
df["odometer"].sort_values().head(10)

23149    0.0
28230    0.0
36174    0.0
36172    0.0
27625    0.0
47055    0.0
31431    0.0
33160    0.0
43612    0.0
36960    0.0
Name: odometer, dtype: float64

In [32]:
df["odometer"].sort_values(ascending=False).head(10)

17869    990000.0
40729    990000.0
48962    980000.0
14245    920000.0
2840     866000.0
32973    840000.0
2440     840000.0
13027    838095.0
41699    831000.0
5735     813542.0
Name: odometer, dtype: float64

In [33]:
df[df["price"] == 1]

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
405,1,2014.0,chevrolet camaro,excellent,6.0,gas,71310.0,automatic,coupe,NaN,NaN,2018-07-14,29
3063,1,1998.0,chevrolet silverado,good,8.0,gas,164000.0,automatic,pickup,NaN,1.0,2018-10-11,49
3808,1,2007.0,chevrolet tahoe,good,8.0,gas,200.0,automatic,SUV,red,NaN,2019-03-18,63
3902,1,1996.0,ford f-150,fair,NaN,gas,163000.0,manual,truck,white,NaN,2019-02-23,54
4140,1,2004.0,chevrolet silverado,excellent,8.0,diesel,83000.0,automatic,pickup,NaN,1.0,2019-02-04,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49699,1,2007.0,chevrolet trailblazer,excellent,8.0,gas,NaN,automatic,SUV,black,1.0,2018-08-06,28
49709,1,NaN,ford f150,excellent,8.0,gas,139700.0,other,pickup,red,1.0,2019-03-11,18
50245,1,1986.0,chevrolet silverado,good,8.0,gas,NaN,automatic,truck,red,1.0,2018-11-30,50
50393,1,2003.0,gmc sierra 2500hd,good,8.0,diesel,212300.0,automatic,pickup,black,1.0,2019-04-12,28
51256,1,2012.0,honda civic lx,excellent,4.0,gas,71262.0,automatic,sedan,blue,NaN,2018-05-06,53

In [34]:
df[df["odometer"] == 0]

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
352,7997,2009.0,gmc yukon,excellent,8.0,gas,0.0,automatic,SUV,white,1.0,2019-03-16,88
814,2995,1999.0,ford f-150,good,6.0,gas,0.0,manual,truck,NaN,NaN,2019-03-14,16
1375,5888,NaN,toyota 4runner,good,6.0,gas,0.0,automatic,SUV,black,NaN,2019-02-22,36
1461,1000,1992.0,gmc sierra 1500,good,8.0,gas,0.0,automatic,truck,NaN,NaN,2018-09-28,47
1970,10988,2000.0,ford f-250 sd,good,8.0,diesel,0.0,automatic,truck,white,1.0,2018-11-21,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...
49170,3300,2002.0,hyundai santa fe,good,6.0,gas,0.0,automatic,wagon,white,1.0,2019-04-14,31
49284,3300,2002.0,hyundai santa fe,good,6.0,gas,0.0,automatic,wagon,white,1.0,2019-02-15,7
50412,25500,NaN,jeep wrangler,good,6.0,gas,0.0,automatic,SUV,yellow,1.0,2018-06-12,48
50631,3600,2012.0,chrysler 200,good,4.0,gas,0.0,automatic,sedan,red,NaN,2018-07-24,90
51189,5000,2001.0,ford mustang,excellent,8.0,gas,0.0,manual,coupe,silver,NaN,2019-01-20,67

In [35]:
missing = df.isna().sum()

missing_percent = (missing / len(df)) * 100

pd.DataFrame({
    "missing": missing,
    "percentage": missing_percent
})

              missing  percentage
price               0    0.000000
model_year       3619    7.023775
model               0    0.000000
condition           0    0.000000
cylinders        5260   10.208637
fuel                0    0.000000
odometer         7892   15.316836
transmission        0    0.000000
type                0    0.000000
paint_color      9267   17.985444
is_4wd          25953   50.369723
date_posted         0    0.000000
days_listed         0    0.000000

In [36]:
df["model_year"].value_counts().sort_index()

model_year
1908.0       2
1929.0       1
1936.0       1
1948.0       1
1949.0       1
          ...
2015.0    3323
2016.0    2954
2017.0    2419
2018.0    2193
2019.0     380
Name: count, Length: 68, dtype: int64

In [37]:
df[df["model_year"].isna()].head(10)

,price,model_year,model,condition,cylinders,fuel,odometer,transmission,type,paint_color,is_4wd,date_posted,days_listed
1,25500,NaN,ford f-150,good,6.0,gas,88705.0,automatic,pickup,white,1.0,2018-10-19,50
20,6990,NaN,chevrolet tahoe,excellent,8.0,gas,147485.0,automatic,SUV,silver,1.0,2018-08-05,28
65,12800,NaN,ford f-150,excellent,6.0,gas,108500.0,automatic,pickup,white,NaN,2018-09-23,15
69,7800,NaN,ford f-150,like new,8.0,gas,97510.0,automatic,truck,white,1.0,2019-02-20,39
72,3650,NaN,subaru impreza,excellent,NaN,gas,74000.0,automatic,sedan,blue,1.0,2018-08-07,60
84,4995,NaN,hyundai elantra,like new,4.0,gas,151223.0,automatic,sedan,custom,NaN,2018-09-15,1
102,10800,NaN,chevrolet colorado,excellent,5.0,gas,114922.0,automatic,truck,red,1.0,2018-06-23,35
114,23700,NaN,nissan frontier crew cab sv,good,6.0,gas,12901.0,other,pickup,black,1.0,2018-09-21,8
116,25300,NaN,chevrolet camaro lt coupe 2d,good,6.0,gas,3568.0,other,coupe,NaN,NaN,2018-06-16,34
144,8995,NaN,chevrolet silverado 1500,excellent,8.0,gas,119726.0,automatic,truck,grey,1.0,2019-03-18,27

In [38]:
df.groupby("model")["model_year"].median()

model
acura tl             2007.0
bmw x5               2010.0
buick enclave        2012.0
cadillac escalade    2009.0
chevrolet camaro     2013.0
                      ...
toyota sienna        2008.0
toyota tacoma        2010.0
toyota tundra        2009.0
volkswagen jetta     2012.0
volkswagen passat    2013.0
Name: model_year, Length: 100, dtype: float64

In [39]:
df.groupby("model")["model_year"].median().isna().sum()

np.int64(0)

In [40]:
median_year_by_model = df.groupby("model")["model_year"].transform("median")

In [41]:
df["model_year"] = df["model_year"].fillna(median_year_by_model)

In [44]:
df.groupby("model")["cylinders"].median()

model
acura tl             6.0
bmw x5               6.0
buick enclave        6.0
cadillac escalade    8.0
chevrolet camaro     6.0
                    ...
toyota sienna        6.0
toyota tacoma        6.0
toyota tundra        8.0
volkswagen jetta     4.0
volkswagen passat    4.0
Name: cylinders, Length: 100, dtype: float64

In [45]:
median_cylinders_by_model = df.groupby("model")["cylinders"].transform("median")

In [46]:
df["cylinders"] = df["cylinders"].fillna(median_cylinders_by_model)

In [47]:
df["cylinders"].isna().sum()

np.int64(0)

In [48]:
df.groupby("model")["odometer"].median()

model
acura tl             141000.0
bmw x5               108500.0
buick enclave        113728.0
cadillac escalade    129176.0
chevrolet camaro      62655.5
                       ...
toyota sienna        140715.0
toyota tacoma        125000.0
toyota tundra        120500.0
volkswagen jetta     107000.0
volkswagen passat     84905.0
Name: odometer, Length: 100, dtype: float64

In [49]:
df.groupby("model")["odometer"].median().isna().sum()

np.int64(1)

In [50]:
odometer_median_by_model = df.groupby("model")["odometer"].median()

odometer_median_by_model[odometer_median_by_model.isna()]

model
mercedes-benz benze sprinter 2500   NaN
Name: odometer, dtype: float64

In [51]:
df["odometer"].median()

np.float64(113000.0)

In [52]:
odometer_median_by_model = df.groupby("model")["odometer"].transform("median")

In [53]:
df["odometer"] = df["odometer"].fillna(odometer_median_by_model)
df["odometer"] = df["odometer"].fillna(df["odometer"].median())

In [ ]:
df["odometer"].isna().sum()

np.int64(0)

In [ ]:
df["paint_color"] = df["paint_color"].fillna("unknown")

df["paint_color"].isna().sum()

np.int64(0)

In [56]:
df["is_4wd"].value_counts(dropna=False)

is_4wd
NaN    25953
1.0    25572
Name: count, dtype: int64

In [57]:
df["is_4wd"] = df["is_4wd"].fillna(0).astype(int)

df["is_4wd"].value_counts()

is_4wd
0    25953
1    25572
Name: count, dtype: int64

In [58]:
df.isna().sum()

price           0
model_year      0
model           0
condition       0
cylinders       0
fuel            0
odometer        0
transmission    0
type            0
paint_color     0
is_4wd          0
date_posted     0
days_listed     0
dtype: int64